---
name: Badges Update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  devcard:
    name: daily.dev badge
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          user_id: ${{ secrets.USER_ID }}
          type: wide
  readme_stats:
    name: GitHub Readme Stats
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download images
      run: |
        wget -O readme_stats.svg  --timeout=20 "https://github-readme-stats-afcm.vercel.app/api?username=AFCMS&count_private=true&include_all_commits=true&show_icons=true"
        wget -O readme_stats_top_langs.svg --timeout=20 "https://github-readme-stats-afcm.vercel.app/api/top-langs/?username=AFCMS&layout=compact&hide_title=false&exclude_repo=fiverr_nanyanghuang_game,fiverr_nanyanguang_main_menu,fiverr_nanyanguang_creative,MCL2FORK,test_amplication"
        wget -O profile_trophies.svg --timeout=20 "https://github-profile-trophy.vercel.app/?username=AFCMS&row=2&column=4"
    
    - name: Commit and push if changed
      run: |
        git add readme_stats.svg readme_stats_top_langs.svg profile_trophies.svg
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git diff-index --quiet HEAD || git commit -m "Update stats images"
        git push
